title: Horta's Home
views:
  - icon: mdi:view-dashboard
    id: Living_Room_Dashboard
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
            - type: vertical-stack
              cards:
              - type: horizontal-stack
                cards:
                  - type: sensor
                    entity:  sensor.time_utc
                  - type: sensor
                    entity: sensor.mailbox

              
              - type: horizontal-stack
                cards:
                - type: light
                  entity: light.living_room_center
                - type: light
                  entity: light.second_floor_light 
              - type: entity-filter
                entities:
                  - entity: light.bottom
                    tap_action: toggle
                  - entity: light.bunker
                    tap_action: toggle
                  - entity: light.bunker_closet
                    tap_action: toggle
                  - entity: light.bunker_stairs
                    tap_action: toggle
                  - entity: light.bunker_studio
                    tap_action: toggle
                  - entity: light.dinner_table
                    tap_action: toggle
                  - entity: light.front_door
                    tap_action: toggle
                  - entity: light.garage_stairs_
                    tap_action: toggle
                  - entity: light.interrutor1
                    tap_action: toggle
                  - entity: light.interrutor2
                    tap_action: toggle
                  - entity: light.kitchen_bench
                    name: Bench
                    tap_action: toggle
                  - entity: light.kitchen_table
                    name: Kitchen
                    tap_action: toggle
                  - entity: light.living_room_center
                    tap_action: toggle
                  - entity: light.outside
                    tap_action: toggle
                  - entity: light.second_floor_light
                    name: 2ยบ Floor
                    tap_action: toggle
                  - entity: light.secretary
                    tap_action: toggle
                  - entity: light.terrace
                    tap_action: toggle
                  - entity: light.wc
                    tap_action: toggle
                  - entity: light.aliceswitchdoor
                    tap_action: toggle
                  - entity: light.laundry
                    tap_action: toggle
                  - entity: light.garagecenter
                    tap_action: toggle
                  - entity: switch.icepc
                    tap_action: toggle
                  - entity: cover.kitchen_left_blinds
                    tap_action: toggle
                    name: Kitchen L
                  - entity: cover.kitchen_right_blinds
                    tap_action: toggle
                    name: Kitchen R
                  - entity: cover.living_room_blinds
                    tap_action: toggle
                  - entity: switch.tree
                    tap_action: toggle
                  - media_player.mediaroom_19216818611
                  - media_player.tv
                  - switch.3d_printer
                  - binary_sensor.0x00158d000288ce89
                  - binary_sensor.0x00158d000288ce83
                  - binary_sensor.0x00158d000288cef3
                  - switch.wax
                state_filter:
                  - 'on'
                  - 'open'
                  - 'playing'
                card: 
                  type: glance
                  show_state: false
              - type: picture-glance
                title: Garage
                entity: camera.garage
                camera_image: camera.garage
                show_info: true
                tap_action: dialog
                entities:
                   - light.pir_garage_stairs
            - type: vertical-stack
              cards:
                - type: glance
                  entities:
                    - device_tracker.iphonebruno
                    - device_tracker.iphonedeana
                    - device_tracker.78d6f0039ed3
                - type: horizontal-stack
                  cards:
                  - type: entity-button
                    entity:  cover.living_room_blinds
                    name: Living Room
                  - type: entity-button
                    name: Kitchen R
                    entity: cover.kitchen_right_blinds
                  - type: entity-button
                    entity: cover.kitchen_left_blinds
                    name: Kitchen L
                  - type: entity-button
                    entity: switch.tree
                    name: Christmas
                    tap_action: toggle
                - type: horizontal-stack
                  cards:
                  - type: entity-button
                    name: Table
                    tap_action: toggle
                    entity: light.dinner_table
                  - type: entity-button
                    entity:  media_player.tv

                  - type: entity-button
                    name: AC
                    entity: climate.air_conditioner
                  - type: entity-button
                    name: Off All
                    icon: mdi:power-standby
                    tap_action: call-service
                    entity:  script.1542842262056
                    service: script.turn_on

                - type: iframe
                  url: https://superbh.com/dash.html
                  aspect_ratio: 63%
  - icon: mdi:chemical-weapon
    id: Bunker_Dashbord
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
            - type: picture-glance
              title: Bunker
              entity: camera.3d_printer
              camera_image: camera.3d_printer
              show_info: true
              tap_action: dialog
              entities:
                - light.bunker
                - light.secretary
                - light.bunker_closet
                - light.bunker_studio
                - light.bunker_stairs
                - switch.3d_printer
            - type: vertical-stack
              cards:
                - type: sensor
                  entity: sensor.bunker_temperature
                  name: Temperature
                  
                - type: sensor
                  entity: sensor.bunker_humidity
                  name: Humidity
            - type: vertical-stack
              cards:
                - type: entity-filter
                  entities:
                    - entity: light.bottom
                      tap_action: toggle
                    - entity: light.bunker
                      tap_action: toggle
                    - entity: light.bunker_closet
                      tap_action: toggle
                    - entity: light.bunker_stairs
                      tap_action: toggle
                    - entity: light.bunker_studio
                      tap_action: toggle
                    - entity: light.dinner_table
                      tap_action: toggle
                    - entity: light.front_door
                      tap_action: toggle
                    - entity: light.garage_stairs_
                      tap_action: toggle
                    - entity: light.interrutor1
                      tap_action: toggle
                    - entity: light.interrutor2
                      tap_action: toggle
                    - entity: light.kitchen_bench
                      name: Bench
                      tap_action: toggle
                    - entity: light.kitchen_table
                      name: Kitchen
                      tap_action: toggle
                    - entity: light.living_room_center
                      tap_action: toggle
                    - entity: light.outside
                      tap_action: toggle
                    - entity: light.second_floor_light
                      name: 2ยบ Floor
                      tap_action: toggle
                    - entity: light.secretary
                      tap_action: toggle
                    - entity: light.terrace
                      tap_action: toggle
                    - entity: light.wc
                      tap_action: toggle
                    - entity: light.aliceswitchdoor
                      tap_action: toggle
                    - entity: light.laundry
                      tap_action: toggle
                    - entity: light.garagecenter
                      tap_action: toggle
                    - entity: switch.icepc
                      tap_action: toggle
                    - entity: cover.kitchen_left_blinds
                      tap_action: toggle
                      name: Kitchen L
                    - entity: cover.kitchen_right_blinds
                      tap_action: toggle
                      name: Kitchen R
                    - entity: cover.living_room_blinds
                      tap_action: toggle
                    - media_player.mediaroom_19216818611
                    - media_player.tv
                    - entity: switch.3d_printer
                      tap_action: toggle
                    - binary_sensor.0x00158d000288ce89
                    - binary_sensor.0x00158d000288ce83
                    - binary_sensor.0x00158d000288cef3
                    - switch.wax
                  state_filter:
                    - 'on'
                    - 'open'
                    - 'playing'
                  card: 
                    type: glance
                    show_state: false
                - type: iframe
                  url: https://superbh.com/dash.html
                  aspect_ratio: 63%
  - icon: mdi:thermometer
    id: Climate
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
            - type: vertical-stack
              cards:
              - type: horizontal-stack
                cards:
                  - type: sensor
                    entity: sensor.alice_temperature

                  - type: sensor
                    entity: sensor.alice_humidity

              - type: horizontal-stack
                cards:
                  - type: sensor
                    entity:  sensor.street_temperature

                  - type: sensor
                    entity:  sensor.street_humidity

              - type: horizontal-stack
                cards:
                  - type: sensor
                    entity:  sensor.garage_temperature

                  - type: sensor
                    entity:  sensor.garage_humidity

            - type: vertical-stack
              cards:
                - type: horizontal-stack
                  cards:
                    - type: sensor
                      entity: sensor.main_room_temperature

                    - type: sensor
                      entity: sensor.main_room_humidity

                - type: horizontal-stack
                  cards:
                    - type: sensor
                      entity: sensor.bunker_temperature

                    - type: sensor
                      entity: sensor.bunker_humidity

  - title: Street
    cards:
      - type: entities
        entities:
          - sensor.mailbox
          - sensor.mailbox_door
          - light.front_door
      - type: entities
        title: Mailbox
        show_header_toggle: true
        entities:
          - sensor.mailbox
          - sensor.last_mail_receive_on
          - sensor.mail_checked_on
          - sensor.mailbox_door
      - type: entities
        title: Entrance
        show_header_toggle: true
        entities:
          - sensor.front_door
          - lock.outdoor_gate
      - type: entities
        title: Sensors
        show_header_toggle: true
        entities:
          - sensor.street_temperature
          - sensor.street_humidity
          - sensor.street_lightbulb
          - sensor.ring_front_door_battery
          - sensor.ring_front_door_last_activity
          - sensor.ring_front_door_last_ding
          - sensor.ring_front_door_last_motion
          - sensor.ring_front_door_volume
          - sensor.ring_front_door_wifi_signal_category
          - sensor.ring_front_door_wifi_signal_strength
  - title: Master Room
    cards:
      - type: entities
        entities:
          - climate.air_conditioner
  - title: Living Room
    cards:
      - type: entities
        entities:
          - cover.living_room_blinds
          - light.living_room_center
          - light.dinner_table
      - type: media-control
        entity: media_player.apple_tv
      - type: media-control
        entity: media_player.mediaroom_19216818611
      - type: media-control
        entity: media_player.tv
  - title: Kitchen
    cards:
      - type: entities
        entities:
          - cover.kitchen_left_blinds
          - cover.kitchen_right_blinds
          - light.kitchen_bench
          - light.kitchen_table
  - title: Bunker
    cards:
      - type: entities
        entities:
          - sensor.social_youtube
          - light.bunker
          - light.secretary
          - light.bunker_closet
          - light.bunker_stairs
          - light.bunker_studio
          - binary_sensor.0x00158d000288ce89
          - binary_sensor.0x00158d000288ce83
      - type: entities
        title: Sensors
        show_header_toggle: true
        entities:
          - sensor.bunker_temperature
          - sensor.bunker_humidity
          - sensor.bunker_lightbulb
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
      - type: entities
        title: Computers
        show_header_toggle: true
        entities:
          - switch.icepc
      - type: entities
        title: 3D Printer
        show_header_toggle: true
        entities:
          - switch.3d_printer
          - binary_sensor.octoprint_printing_error
          - binary_sensor.octoprint_printing
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_actual_tool0_temp
          - sensor.octoprint_current_state
          - sensor.octoprint_job_percentage
          - sensor.octoprint_target_bed_temp
          - sensor.octoprint_target_tool0_temp
      - type: picture-entity
        title: 3D Printer
        entity: camera.3d_printer
        camera_image: camera.3d_printer
        show_info: true
        tap_action: dialog
  - title: Terrace
    cards:
      - type: entities
        entities:
          - light.terrace
  - title: Garage
    cards:
      - type: entities
        entities:
          - lock.garage_gate
          - light.garagecenter
          - light.laundry
          - light.outside
          - light.bottom
          - light.pir_garage_stairs
      - type: picture-entity
        title: Garage
        entity: camera.garage
        camera_image: camera.garage
        show_info: true
        tap_action: dialog
      - type: entities
        title: Sensors
        show_header_toggle: true
        entities:
          - sensor.garage_temperature
          - sensor.garage_humidity
          - sensor.garage_lightbulb
  - title: Alice Room
    cards:
      - type: entities
        entities:
          - light.aliceswitchdoor
          - sensor.0x00158d000239ab26_humidity
          - sensor.0x00158d000239ab26_temperature
  - title: Rita Studio
    panel: true
    cards:
      - type: entities
        entities:
          - switch.wax